"""add_amount_tendered_and_change_to_payments

Revision ID: 54162e394e0a
Revises: db96da825119
Create Date: 2025-10-27 07:35:08.998067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54162e394e0a'
down_revision: Union[str, Sequence[str], None] = 'db96da825119'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('amount_tendered', sa.Float(), nullable=True))
    op.add_column('payments', sa.Column('change', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'change')
    op.drop_column('payments', 'amount_tendered')
    # ### end Alembic commands ###
