"""add_markup_percentage_to_purchase_items

Revision ID: d5125287da62
Revises: 54162e394e0a
Create Date: 2025-10-27 07:41:07.474240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5125287da62'
down_revision: Union[str, Sequence[str], None] = '54162e394e0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_items', sa.Column('markup_percentage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_items', 'markup_percentage')
    # ### end Alembic commands ###
