"""add_selling_price_to_purchase_items

Revision ID: ef9472e21f33
Revises: d5125287da62
Create Date: 2025-10-27 08:21:02.857796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef9472e21f33'
down_revision: Union[str, Sequence[str], None] = 'd5125287da62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_items', sa.Column('selling_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_items', 'selling_price')
    # ### end Alembic commands ###
